blog/urls.py
# .py file is used for linking to other pages
from django.urls import path
from .views import PostCreateView, PostUpdateView, PostDeleteView, UserPostListView
# import views.py in order to use home function (for linking)
from . import views

# second parameter is either a class based view or a view function (imported)
urlpatterns = [
    path('', views.home, name='blog-home'),
    path('about/', views.about, name='blog-about'),
    path('post/<int:pk>', views.detail, name='post-detail'),
    path('post/new', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('liked/', views.liked, name="user-likes"),
    path('messages/', views.chat, name="messages"),
    path('like/', views.like, name='like'),
    path('pin/', views.pin, name='pin'),
    path('unpin/', views.unpin, name='unpin'),
    path('unlike/', views.unlike, name='unlike'),
    path('messages/messagesend/', views.messagesend, name='messagesend'),
    path('messages/<str:username>', views.messagesPerson, name="messages-person")
]

django_posts/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as users_views
from django.conf import settings
from django.conf.urls.static import static

# list of url patterns that have a path associated with them
urlpatterns = [
    path('admin/', admin.site.urls),
    # /blog will map to blog.urls(.py), and there we have path that maps
    # onto views.(py)home(func)
    path('', users_views.home, name="home"),
    path('ajax/', include('blog.urls')),
    path('blog/', include('blog.urls')),
    path('register/', users_views.register, name="register"),
    path('profile/', users_views.profile, name="profile"),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name="password_reset_confirm"),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name="password_reset_complete"),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import datetime

class Post(models.Model): 
  title = models.CharField(max_length=100)
  content = models.TextField()
  date_posted = models.DateTimeField(default=timezone.now)
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  pin = models.BooleanField(default=False)

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse('post-detail', kwargs={'pk': self.pk})

class Comment(models.Model):
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  content = models.TextField()
  date_posted = models.DateTimeField(default=timezone.now)
  post = models.ForeignKey(Post, on_delete=models.CASCADE)

  def __str__(self):
    return self.content

class Like(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  post = models.ForeignKey(Post, on_delete=models.CASCADE)
  date_liked = models.DateTimeField(default=timezone.now)

  def __str__(self):
    return f'{self.user.username} liked a post'

# can have two foreign keys to the same model, but need a related_name
class Message(models.Model):
  sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
  receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
  message = models.CharField(max_length=560)
  date_sent = models.DateTimeField(default=timezone.now)
  color = models.CharField(max_length=20, default="regular-blue")

  def __str__(self):
    return f'{self.sender.username} sent {self.receiver.username} "{self.message}"'

class Todo(models.Model):
  completed = models.BooleanField(default=False)
  due_date = models.DateTimeField()
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  todo = models.CharField(max_length=140)

  def __str__(self):
    return self.todo

blog/forms.py
from django import forms
from .models import Comment, Message, Todo, Post

# each model requires a form (if needed) and a class Meta, which
# specifies the model and fields that will be displayed
# (forms don't always need to be specified (can be manually made))
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['due_date', 'todo']

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

blog/views.py
# needed to redirect and render pages from templates
# get_object_or_404: use to get an object using a specific field inside that model
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect

# needed to restrict some pages to users who are logged in 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# make sure to import all models/forms that are used
from django.contrib.auth.models import User
from .forms import CommentForm, MessageForm, TodoForm, PostForm
from .models import Post, Comment, Like, Message, Todo
from django.utils import timezone

# views, pagination, messages, others
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
import math

# not using class based views for home/detail (bigger views)

def home(request):

  # separating pinned/unpinned posts to put pinned on top (still ordering by date)
  post_all_pinned = Post.objects.filter(pin=True)
  post_all_unpinned = Post.objects.filter(pin=False)
  post_all_pinned = post_all_pinned.order_by('-date_posted')
  post_all_unpinned = post_all_unpinned.order_by('-date_posted')
  post_all_pinned = list(post_all_pinned)
  post_all_unpinned = list(post_all_unpinned)

  post_all = post_all_pinned + post_all_unpinned

  # stats count
  if request.user.is_authenticated:
    posts_by_me = Post.objects.filter(author=request.user)
    comments_by_me = Comment.objects.filter(author=request.user)
    likes_by_me = Like.objects.filter(user=request.user)
  else:
    posts_by_me = Post.objects.filter(title="not in")
    comments_by_me = Comment.objects.filter(content="comment")
    likes_by_me = Like.objects.filter()

  # populate list_likes with post.pk of posts that have been liked by the user that is logged in
  list_likes = []

  if request.user.is_authenticated:
    likes = Like.objects.filter(user=request.user)
    likes_count = likes.count()

    for liked_posts in likes:
      list_likes.extend([liked_posts.post.pk])

  # pass in all likes
  likes = Like.objects.all()

  # 10, 5, 1
  post_count = posts_by_me.count()
  post_count_10 = post_count // 10
  post_count_5 = (post_count - (post_count_10 * 10)) // 5
  post_count_1 = (post_count - (post_count_10 * 10) - (post_count_5 * 5))

  comment_count = comments_by_me.count()
  comment_count_10 = comment_count // 10
  comment_count_5 = (comment_count - (comment_count_10 * 10)) // 5
  comment_count_1 = (comment_count - (comment_count_10 * 10) - (comment_count_5 * 5))

  like_count = likes_by_me.count()
  like_count_10 = like_count // 10
  like_count_5 = (like_count - (like_count_10 * 10)) // 5
  like_count_1 = (like_count - (like_count_10 * 10) - (like_count_5 * 5))

  # can write our own function inside a function to make valid form handling easier
  def form_valid(form, request):

    # since author/post/date_posted is not explicitly defined inside the form, we want to save everything we have
    # so far (commit = False), and using the same object, fill in the other entries
    modelForm = form.save(commit = False)
    modelForm.author = request.user
    modelForm.date_posted = timezone.now()
    modelForm.pin = False
    modelForm.save()
    return redirect('blog-home')

  if request.method == "POST":
    form = PostForm(request.POST)
    if form.is_valid():
      return form_valid(form, request)
  else:
    form = PostForm()

  # context includes now all posts (in pinned/unpinned order), array of all posts liked, and page #
  context = {
    'posts': post_all,
    'likes_list': list_likes,
    'likes': likes,
    'posts_by_me': post_count,
    'number_by_me_10': [0] * int(post_count_10),
    'number_by_me_5': [0] * int(post_count_5),
    'number_by_me_1': [0] * int(post_count_1),
    'comments_by_me': comment_count,
    'comment_by_me_10': [0] * int(comment_count_10),
    'comment_by_me_5': [0] * int(comment_count_5),
    'comment_by_me_1': [0] * int(comment_count_1),
    'likes_by_me': like_count,
    'like_by_me_10': [0] * int(like_count_10),
    'like_by_me_5': [0] * int(like_count_5),
    'like_by_me_1': [0] * int(like_count_1),
    'form': form,
  }

    # # if form has been submitted -- all "forms" are in the form of submit buttons with hidden input lines
    # if request.method == "POST":
      
    #   # used to process which submit button was clicked, the others will return False (best solution?)
    #   postID_pin = request.POST.get('pinned', False)
    #   postID_unpin = request.POST.get('unpinned', False)
    #   like = request.POST.get('like', False)
    #   unlike = request.POST.get('unlike', False)

    #   username = request.user.username

    #   # if unpin button is clicked, we can retrieve the affected post by postID and SAVE it (important!)
    #   if postID_unpin != False:
    #     obj = get_object_or_404(Post, pk=postID_unpin)
    #     obj.pin = False
    #     obj.save()
    #     messages.info(request, f'Unpinned your post "{obj.title}"')
    #     return HttpResponseRedirect(request.META.get('HTTP_REFERER')) # allows redirect to the same page in pagination
      
    #   elif postID_pin != False:
    #     user = get_object_or_404(User, username=username)
    #     posts = Post.objects.filter(author=user, pin=True)
    #     pinnedCount = posts.count()
        
    #     if pinnedCount == 2:
    #       messages.error(request, f'Cannot pin more than 2 posts.')
    #       return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        
    #     else:
    #       obj = get_object_or_404(Post, pk=postID_pin)
    #       obj.pin = True
    #       obj.save()
    #       messages.warning(request, f'Pinned your post! "{obj.title}"')
    #       return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    # # creates/deletes a new Like model for every like/unlike
    # elif like != False:
    #   user_like = get_object_or_404(User, username=username)
    #   post_like = get_object_or_404(Post, pk=like)
    #   like_model = Like(user=user_like, post=post_like)
    #   like_model.save()

    #   messages.success(request, f'''You liked {post_like.author.username}'s post, "{post_like.title}"''')
    #   return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    # elif unlike != False:
    #   user_unlike = get_object_or_404(User, username=username)
    #   post_unlike = get_object_or_404(Post, pk=unlike)
    #   like_to_delete = get_object_or_404(Like, user=user_unlike, post=post_unlike)
    #   like_to_delete.delete()
    #   messages.success(request, f'''You unliked {post_unlike.author.username}'s post, "{post_unlike.title}"''')
    #   return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

  return render(request, 'blog/home2.html', context)

def like(request):
  if request.method == "GET":
    post_pk = request.GET['post_pk']
    like_user = request.GET['like_user']
    liked_post = Post.objects.get(pk=post_pk)
    liked_user = User.objects.get(username=like_user)
    new_like = Like(user=liked_user, post=liked_post)
    new_like.save()
    return HttpResponse('success')
  else:
    return HttpResponse('unsuccessful')

def unlike(request):
  if request.method == "GET":
    post_pk = request.GET['post_pk']
    like_user = request.GET['like_user']
    liked_post = Post.objects.get(pk=post_pk)
    liked_user = User.objects.get(username=like_user)
    old_like = get_object_or_404(Like, user=liked_user, post=liked_post)
    old_like.delete()
    return HttpResponse('success')
  else:
    return HttpResponse('unsuccessful')

def pin(request):
  if request.method == "GET":
    post_pk = request.GET['post_pk']
    post_to_pin = Post.objects.get(pk=post_pk)
    post_to_pin.pin = True
    post_to_pin.save()
    return HttpResponse('success')
  else:
    return HttpResponse('unsuccessful')

def unpin(request):
  if request.method == "GET":
    post_pk = request.GET['post_pk']
    post_to_pin = Post.objects.get(pk=post_pk)
    post_to_pin.pin = False
    post_to_pin.save()
    return HttpResponse('success')
  else:
    return HttpResponse('unsuccessful')

# same as home view with less functionality, but in a Class based view
class UserPostListView(ListView):
  model = Post
  template_name = 'blog/user_posts.html'
  context_object_name = 'posts'

  def get_queryset(self):
    user = get_object_or_404(User, username=self.kwargs.get('username'))
    return Post.objects.filter(author = user).order_by('-date_posted')

# login required to view page (will redirect to login)
@login_required
def detail(request, *args, **kwargs):

  # can write our own function inside a function to make valid form handling easier
  def form_valid(form, request):

    # since author/post/date_posted is not explicitly defined inside the form, we want to save everything we have
    # so far (commit = False), and using the same object, fill in the other entries
    obj = get_object_or_404(Post, pk=kwargs['pk'])
    modelForm = form.save(commit = False)
    modelForm.post = obj
    modelForm.author = request.user
    modelForm.date_posted = timezone.now()
    modelForm.save()
    return redirect('post-detail', pk=kwargs['pk'])

  # if not valid form, simply returns
  if request.method == "POST":
    form =  Form(request.POST)
    if form.is_valid():
      messages.success(request, f'commented!')
      return form_valid(form, request)
  else:
    form = CommentForm()

  # passes in all comments/likes to display in details
  obj = get_object_or_404(Post, pk=kwargs['pk'])
  comments = Comment.objects.filter(post=obj)
  comments = list(comments)
  likes = Like.objects.filter(post=obj)
  likes = list(likes)
  context = {
    'post': obj,
    'comments': comments,
    'form': form,
    'likes': likes,
  }

  return render(request, 'blog/post_detail.html', context)
 
# simple create view overwriting form_valid

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

<!-- May think about adding a 'todo' list for people who want to make 
a todo list for whatever reason. Form submit = POST -->

{% block content %}
  <h1> About Page </h1>
{% endblock content %}

blog/templates/blog/likes.html
{% extends "blog/base.html" %}
{% block content %}
<h1 class="mb-3 user-posts"> {{ request.user.username }}'s Liked Posts </h1>

<!-- still separation of pinned/regular posts -->
{% for like in likes %}
{% if like.post.pin == True %}
<div id="post" class="post-pinned">

  {% else %}
  <div id="post">

    {% endif %}

    <div id="post-head">

      <img src="{{ like.post.author.profile.image.url }}" class="post-image" />

      <div id="heading">
        <a href="{% url 'user-posts' like.post.author.username %}" class="hover">
          <p class="post-name"> {{ like.post.author.username }} </p>
        </a>
        <small class="text-muted date"> {{ like.post.date_posted }}</small>
      </div>
      {% if like.post.pin == True %}
      <p class="post-title pinned">{{ like.post.title }}</p>

      {% else %}
      <p class="post-title">{{ like.post.title }}</p>

      {% endif %}

    </div>

    {% if like.post.pin == True %}
    <div id="post-content" class="pinned-color no-border">

      {% else %}
      <div id="post-content" class="no-border">

        {% endif %}

        {{ like.post.content|linebreaks }}
        <div id="elipsis-user">
          <a href="{% url 'post-detail' like.post.id %}"><i class="fas fa-ellipsis-h"></i></a>
        </div>
      </div>
    </div>
    {% endfor %}

    {% endblock content %}

blog/templates/blog/messages_person.html
{% load crispy_forms_tags %}

<!-- makes it so we can load static files from directory-->
{% load static %}
<!-- PUT ALL HTML THAT YOU WANT IN THIS PAGE FOR HOME.HTML-->
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- adding our own .css files from static -->
  <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="{% static 'users/images/favicon.ico' %}"/>
  <script src="https://kit.fontawesome.com/59df0f1cf2.js" crossorigin="anonymous"></script>
  
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

</head>

<body>
  <img src="{% static 'users/images/wolverine-bit.png' %}" class="fixed">  

  <main role="main" class="container full-height">
    <div class="row" style="margin-top: 0px !important;">
      <a href="{% url 'home' %}">
      </a>
      <div id="nav-bar">
        <a class="item float-left" href="{% url 'blog-home' %}"><i class="fas fa-house-user"></i> Home</a>
        <a class="item float-left is-selected" href="{% url 'messages' %}"><span style="font-size: 0.9em"><i class="fas fa-comment-alt"></i></span> Messages</a>
        {% if user.is_authenticated == False %}
          <a class="item float-right" href="{% url 'login' %}"><span style="font-size: 0.9em"><i class="fas fa-sign-in-alt"></i></span> Login</a>
          <a class="item float-right" href="{% url 'register' %}"><span style="font-size: 0.9em"><i class="fas fa-user-plus"></i></span> Register</a>
        {% else %}
          <a class="item float-right" href="{% url 'logout' %}"><span style="font-size: 0.9em"><i class="fas fa-sign-out-alt"></i></span> Logout</a>
          <a class="item float-right" href="{% url 'profile' %}"><span style="font-size: 0.9em"><i class="fas fa-user-circle"></i></span> Profile</a>
          <a class="item float-right" href="{% url 'post-create' %}"><span style="font-size: 0.9em"><i class="fas fa-plus-square"></i></span> New Post</a>
        {% endif %}

      </div>
    </div>

    <div class="row" style="width:100%">

      <div class="col-md-11 no-pad">

      {% if messages %}
        {% for message in messages %}

        {% if message.tags == 'error' %}
        <div class="alert alert-danger"> {{ message }} </div>
        {% else %}
        <div class="alert alert-{{ message.tags }}"> {{ message }} </div>
        {% endif %}

        {% endfor %}
      {% endif %}      

      <div class="head">
        <img class="post-image" src="{{ user_to_message.profile.image.url }}" style="float:left;">
        <div style="float:left;">
          <a class="message-name" href="{% url 'user-posts' user_to_message.username %}"><p class="message-name larger"> {{ user_to_message.username }}</p></a>
          <small class="text-muted date previous-message"> Previous Message History </small> 

        </div>    
      </div>

      <div class="all-messages" id="all-messages">
          {% for m in messages_all %}
              {% if m.sender.username == username_logged_in %}
                  <p class="message-sent {{ m.color }}"> {{ m.message }} </p>
              {% else %}
                  <p class="message-received"> {{ m.message }} </p>
              {% endif %}
          {% endfor %}
      </div>

      <div class="message" id="messages-only">
        <div id="message-form-color" class="message-form" data-color={{color_message}}> {{ form|crispy }} </div>
        <button id="message-send-button" data-username="{{ receiver_username }}" class="send-button float-right send-{{ color_message }}" onclick="new_message(this);"><i class="fas fa-paper-plane"></i></button>
      </div>

    </div>

    <script type="text/javascript">
      $('label').remove();
      var element1 = document.getElementById('message-form-color');
      var element = document.getElementById('message-send-button');
      var color = element1.dataset.color;
      $('#id_message').remove();
      $('#div_id_message').html('<input type="text" name="message" maxlength="560" class="'+color+'" required="" id="id_message" onclick="new_message(this);" data-username="'+element.dataset.username+'" placeholder="Type a message...">');
      $('#id_message').focus();
     
      $('#id_message').keypress(function (e) {
        var key = e.which;
        if(key == 13)  // the enter key code
          {
            $('#id_message').click();
            return false;  
          }
      });  

      var element = document.getElementById('all-messages');
      element.scrollTop = element.scrollHeight;

      function new_message(ele) {

        var text = document.querySelector('#id_message').value;
        var element = document.getElementById('all-messages');
        if (text != "") {
          var receiver = ele.dataset.username;
          $.ajax({
            url: "messagesend/",
            data: {
              receiver_username: ele.dataset.username,
              message_text: text,
              color_message: color,
            },
          });
          $('.all-messages').append('<p class="message-sent '+color+'">'+text+'</p>');
          document.querySelector('#id_message').value = '';
          element.scrollTop = element.scrollHeight;
        }
      }

    </script>

    <div class="col-md-1 no-pad colors">
      <!-- simple way of listing out all available colors (loop?) -->
      <div class="color-palette">   
            
        <form method="POST" action="/blog/messages/">
          {% csrf_token %}
          <input type="hidden" name="color" value="lavendar">
          <input type="hidden" name="receiver" value="{{ user_to_message.username }}">
          <button class="lavendar circle white" type="submit" value="lavendar">
          {% if color_message == "lavendar" %}
              <i class="fas fa-check fa-2x"></i>
          {% endif %}
          </button>
        </form>

        <form method="POST" action="/blog/messages/">
          {% csrf_token %}
          <input type="hidden" name="color" value="dark-pink">
          <input type="hidden" name="receiver" value="{{ user_to_message.username }}">
          <button class="dark-pink circle white" type="submit" value="dark-pink">
          {% if color_message == "dark-pink" %}
              <i class="fas fa-check fa-2x"></i>
          {% endif %} 
          </button>
        </form>

        <form method="POST" action="/blog/messages/">
          {% csrf_token %}
          <input type="hidden" name="color" value="red">
          <input type="hidden" name="receiver" value="{{ user_to_message.username }}">
          <button class="red circle white" type="submit" value="red">
          {% if color_message == "red" %}
              <i class="fas fa-check fa-2x"></i>
          {% endif %}
          </button>
        </form>

        <form method="POST" action="/blog/messages/">
          {% csrf_token %}
          <input type="hidden" name="color" value="orange">
          <input type="hidden" name="receiver" value="{{ user_to_message.username }}">
          <button class="orange circle white" type="submit" value="orange">
          {% if color_message == "orange" %}
              <i class="fas fa-check fa-2x"></i>
          {% endif %}
          </button>
        </form>

        <form method="POST" action="/blog/messages/">
          {% csrf_token %}
          <input type="hidden" name="color" value="yellow">
          <input type="hidden" name="receiver" value="{{ user_to_message.username }}">
          <button class="yellow circle white" type="submit" value="yellow">
          {% if color_message == "yellow" %}
              <i class="fas fa-check fa-2x"></i>
          {% endif %}
          </button>
        </form>

        <form method="POST" action="/blog/messages/">
          {% csrf_token %}
          <input type="hidden" name="color" value="green">
          <input type="hidden" name="receiver" value="{{ user_to_message.username }}">
          <button class="green circle white" type="submit" value="green">
          {% if color_message == "green" %}
              <i class="fas fa-check fa-2x"></i>
          {% endif %}
          </button>
        </form>

        <form method="POST" action="/blog/messages/">
          {% csrf_token %}
          <input type="hidden" name="color" value="light-blue">
          <input type="hidden" name="receiver" value="{{ user_to_message.username }}">
          <button class="light-blue circle white" type="submit" value="light-blue">
          {% if color_message == "light-blue" %}
              <i class="fas fa-check fa-2x"></i>
          {% endif %}
          </button>
        </form>

        <form method="POST" action="/blog/messages/">
          {% csrf_token %}
          <input type="hidden" name="color" value="regular-blue">
          <input type="hidden" name="receiver" value="{{ user_to_message.username }}">
          <button class="regular-blue circle white" type="submit" value="regular-blue">
          {% if color_message == "regular-blue" %}
              <i class="fas fa-check fa-2x"></i>
          {% endif %}
          </button>
        </form>

        <form method="POST" action="/blog/messages/">
          {% csrf_token %}
          <input type="hidden" name="color" value="purple">
          <input type="hidden" name="receiver" value="{{ user_to_message.username }}">
          <button class="purple circle white" type="submit" value="purple">
          {% if color_message == "purple" %}
              <i class="fas fa-check fa-2x"></i>
          {% endif %} 
          </button>
        </form>

      </div>
    </div>


    </div>

  </main>

</body>

</html>

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div id="post" class="top-margin"> 

    <div id="post-head">
      <img draggable="false" src="{{ request.user.profile.image.url }}" class="post-image" />

      <div id="heading">
        <a href="{% url 'user-posts' request.user.username %}" class="hover">
          <p class="post-name top-margin"> {{ request.user.username }} </p>
        </a>
        <small class="text-muted date top-margin"> {% now "F n, Y, g:i a" %} </small>            
      </div>

      <form method="POST">
        {% csrf_token %}
          {{ form|crispy }}
          <button class="item float-right post-confirm" type="submit"><span style="font-size: 0.9em"><i class="fas fa-share-square"></i></span> Post! </button>
        {% if post.author == user %}
        <a class="item float-left post-confirm ml-2" href="{% url 'post-delete' post.id %}"><span style="font-size: 0.9em"><i class="fas fa-trash-alt"></i></span> Delete Post</a>
        {% endif %}
      </form>
    </div>
  </div>

  <script type="text/javascript">
    $('label').remove();
    $('#id_title').attr('placeholder', "Click to add title!");
    $('#id_content').attr('placeholder', "What's on your mind?");

    var element = document.getElementsByClassName('is-selected');
    for (var x = 0; x < element.length; ++x) {
        element[x].classList.remove('is-selected');
    }
    element = document.getElementById('post-button');
    element.classList.add('is-selected');

  </script>

{% endblock content %}